// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJnSwuefS6CXMHBQM8I1mM2Vd9p8AgO3w',
    appId: '1:1062360158608:web:3ecf881b71cc0bad0aa315',
    messagingSenderId: '1062360158608',
    projectId: 'water-delivery-app-2dce8',
    authDomain: 'water-delivery-app-2dce8.firebaseapp.com',
    storageBucket: 'water-delivery-app-2dce8.firebasestorage.app',
    measurementId: 'G-GEY4PL98RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe01sAY6mgkrFCSGv-yAhYUrvr-6nJDhQ',
    appId: '1:1062360158608:android:f719907c6948c3b90aa315',
    messagingSenderId: '1062360158608',
    projectId: 'water-delivery-app-2dce8',
    storageBucket: 'water-delivery-app-2dce8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmknDmw-1mic-ei_vD13KNZFGWAbdAQf4',
    appId: '1:1062360158608:ios:8cf7776c9dda18ae0aa315',
    messagingSenderId: '1062360158608',
    projectId: 'water-delivery-app-2dce8',
    storageBucket: 'water-delivery-app-2dce8.firebasestorage.app',
    iosBundleId: 'com.example.waterDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmknDmw-1mic-ei_vD13KNZFGWAbdAQf4',
    appId: '1:1062360158608:ios:8cf7776c9dda18ae0aa315',
    messagingSenderId: '1062360158608',
    projectId: 'water-delivery-app-2dce8',
    storageBucket: 'water-delivery-app-2dce8.firebasestorage.app',
    iosBundleId: 'com.example.waterDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJnSwuefS6CXMHBQM8I1mM2Vd9p8AgO3w',
    appId: '1:1062360158608:web:c465ecabdd64b63a0aa315',
    messagingSenderId: '1062360158608',
    projectId: 'water-delivery-app-2dce8',
    authDomain: 'water-delivery-app-2dce8.firebaseapp.com',
    storageBucket: 'water-delivery-app-2dce8.firebasestorage.app',
    measurementId: 'G-GQMTB6P3JZ',
  );
}
